=== lkcsi/goapi-test/src/test/resources/book-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "book",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "quantity": {
      "type": "number",
      "minimum": 0
    }
  }
}

=== lkcsi/goapi-test/src/test/resources/initial-data.json
[
  {
    "id": "5d7d1e49-4183-4489-8646-8711c113b672",
    "title": "Title_2",
    "author": "Author_2",
    "quantity": 1
  },
  {
    "id": "694606c3-671c-4297-9a8b-1b87f39b8422",
    "title": "Title_4",
    "author": "Author_4",
    "quantity": 3
  },
  {
    "id": "a4d5396b-dd25-499e-93f7-836a41772ba6",
    "title": "Title_3",
    "author": "Author_3",
    "quantity": 2
  },
  {
    "id": "bdecc1de-8b7d-4bf0-8154-f29d22b72be4",
    "title": "Title_1",
    "author": "Author_1",
    "quantity": 0
  }
]
